### ISSUE TITLE
URGENT: UPDATE RSVP ERROR MESSAGE

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#105]
Hi @JasonTheAdams so the RSVP error message needs to be updated. This is the message that is displayed when a User is logged in and tries to RSVP to an event using the "RSVP form" but have not completed all of their Volunteer Requirements.

**CURRENT:** Thank you for starting the process of volunteering with SD Refugee Tutoring. Currently, you are not yet eligible to volunteer for tutoring events. Please go to your [Profile Page](https://sdrefugeetutoring.com/my-profile) to review your status and finish your required items.

**UPDATED:** Thank you for wanting to tutor with us! Currently, you are not yet eligible to volunteer for tutoring events. Please go to the [Volunteer Portal](https://sdrefugeetutoring.com/volunteer-portal/requirements) to review your status and finish your required items.

You can see this displayed when switched to User: Kathryn Schuyler and trying to RSVP for this event: https://sdrefugeetutoring.com/event/2023-refresher-jan10/

**Comment by JasonTheAdams** [comment]
All set! Taken care of in 4bc8b07

**Comment by dreazee** [comment]
@JasonTheAdams  Awesome! When you get a chance if you can change the link to go directly to the Requirements page, that would be helpful  - https://sdrefugeetutoring.com/volunteer-portal/requirements
Thank youuuuuuuuu!

**Comment by JasonTheAdams** [comment]
Ah yeah, good call! Updated in 8bccb38
