### ISSUE TITLE
[Low] Prevent Portal from including Event drafts (non-published events) into the Upcoming Events list

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#108]
Hey @JasonTheAdams
So Event Drafts are being pulled into the Portal-Upcoming Events list even though they have not been published. These do not show up on the calendar, but DO show up in the Portal.
(There is a way to exclude event drafts from showing up in the Portal—to set the 'Event Option' to "Hide From Event Listings". But doing that then causes more issues when wanting to publish. And it would be nice to really only have properly published events be included in the Upcoming Events!)

**Comment by JasonTheAdams** [comment]
Huh, wow, I'm surprised I have to specify that we only want published events for The Events Calendar API. Hahah! In any case, this is resolved in 867ed08.

**Comment by dreazee** [comment]
@JasonTheAdams haha. SO AM I! Oh, WordPress never fails to "impress" me. THANK YOU!
