### ISSUE TITLE
Add Email copy settings-menu

### ISSUE THREAD

**Issue by mathetos** [SDRefugeeTutoring/sdrt-custom-functions#11]
There's a couple emails that get sent automatically. We should add an Emails settings page as a sub-menu of the RSVP menu item.

It should have Editor screens for each of the emails so SDRT Leadership can change/update the text as they want.

**Comment by dreazee** [comment]
This would be very useful!

**Comment by mathetos** [comment]
@dreazee -- this is already implemented on the site actually. It's a sub-menu of the RSVP menu. See here:

![image](https://user-images.githubusercontent.com/930724/52892073-23d1cd00-3144-11e9-9d49-e727dae049d1.png)
