### ISSUE TITLE
Alter RSVP Window in Volunteer Portal to End-of-Day instead of Event Start Time

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#115]
Oh hi @JasonTheAdams ... Long time! We need Events to not disappear from the Volunteer Portal until 11:59 p.m. on the day of the event. Right now they disappear at the Event Start Time. 
**Background:** Many tutors show up to tutoring and haven't signed up yet. Although this is not ideal, it is the reality. It would be great for them to have an option to RSVP in the Portal (as they are used to) as they are walking up to tutoring, waiting for their student, or even when they get home for the night. Yes, they can still do that from the Calendar Event page, but they are unfamiliar with this and I'd like for them to have the option to do this where they are used to - in the Volunteer Portal. This will also help to train them to RSVP in that place for future dates, maybe even at the same time.

**Comment by dreazee** [comment]
Hi @JasonTheAdams 
Just wanted to poke about this... Is this possible?

**Comment by JasonTheAdams** [comment]
This makes sense! Resolved in 48a92a5

**Comment by dreazee** [comment]
Hi Jason. This hasn't been resolved. Someone tried to rsvp for today's
session after 5pm and it didn't show up.
I double-checked this and it only shows Jan 11.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

It really helps things work better if I actually remember to deploy the files to the live server after I'm done working. 😅

Sorry about that! It should be working, now! Please let me know if it isn't!
