### ISSUE TITLE
CHANGE RSVP FORM MESSAGE ON EVENT PAGE WHEN SOMEONE HAS ALREADY RSVP'D

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#116]
![RSVP message](https://github.com/SDRefugeeTutoring/sdrt-custom-functions/assets/47679296/65f9e906-6751-4484-87a6-e4d710ef6a09)
@JasonTheAdams Sooo... 2nd line of this message needs to be changed as it instructs someone to email info@ to cancel. We want to point people to the Volunteer Portal. So we need the second line of the message: "Need to cancel? ..." to be changed. 
I tried to do this on the RSVP Form in WP but didn't see how I could do that... How can this be done? 

**NEW 2ND LINE:** 
"Need to cancel? Please go to the [Volunteer Portal here](https://sdrefugeetutoring.com/volunteer-portal/upcoming-events) and change your RSVP from 'yes' to 'no.
Thank you for keeping us up-to-date!"

**Comment by JasonTheAdams** [comment]
Good suggestion! Resolved in 92ad557
