### ISSUE TITLE
Remove Trimester Dropdown Menu in the Volunteer Portal/Upcoming Events section

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#120]
Hi @JasonTheAdams  
We already discussed this at length via email but putting this here so it will be official. 

Remove trimester dropdown menu in the Upcoming Events section of the Volunteer Portal:
https://sdrefugeetutoring.com/volunteer-portal/upcoming-events/

**Comment by JasonTheAdams** [comment]
This was resolved in b0692011e80150d4604365be656495c696e899bc, so I'm closing this.
