### ISSUE TITLE
Manually create Background Check Invites and Users

### ISSUE THREAD

**Issue by mathetos** [SDRefugeeTutoring/sdrt-custom-functions#13]
Sometimes the form doesn't create the Candidate ID/Invite correctly. In those cases, it would be easiest if an Admin could create the invite/user manually. I believe the Checkr API supports that functionality, so let's look into it.

**Comment by mathetos** [comment]
Let's have all this functionality in the User Edit screen, where it shows the user background check status:
![image](https://user-images.githubusercontent.com/930724/102542566-db003d80-4066-11eb-8877-251e86a7b377.png)

**Comment by JasonTheAdams** [comment]
Closing in favor of #39 as they're describing the same issue.
