### ISSUE TITLE
feat: add reporting for volunteer attendance

### ISSUE THREAD

**Issue by mathetos** [SDRefugeeTutoring/sdrt-custom-functions#16]
Give the ability to report on how many times people have attended sessions in a spreadsheet for fundraising and reporting purposes.

**Comment by dreazee** [comment]
@mathetos HIGH PRIORITY

**Comment by mathetos** [comment]
Closing in favor of https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/28
