### ISSUE TITLE
Error message during Orientation RSVP

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#18]
Only one out of the last eight people were able to RSVP successfully. Attached is a screenshot of an example of the error message.

That specific error message was also given when user Mona Roshan was trying to RSVP to an Orientation event. 
I was able to replicate it when entering only her first, last, and email address. When trying her first name, last name, and email address I was able to RSVP. info@sdrefugeetutoring.com also works as a valid email.

Error message: 
"The resource submitted could not be validated. For field-specific details, see the 'errors' array."

Event link:
https://sdrefugeetutoring.com/event/fall-2019-orientation-2/

**Comment by mathetos** [comment]
@dreazee I was able to replicate that problem. Isolated the issue to something with the spam protection. I've disabled that for now in the hopes it'll be more stable, but I'll follow up with the plugin author so we can continue to get good spam protection.
