### ISSUE TITLE
User Accounts not being created with Registration Form completion

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#20]

**Comment by dreazee** [comment]
Just wanted to make it official here so I can track any progress!

**Comment by mathetos** [comment]
I have a feeling this is related to #18 that I just closed. But I'll test a bit more later.

**Comment by dreazee** [comment]
I actually received 2 email notifications of New Users yesterday! Starting at 1:15pm.
I received one Monday, too, but there was no background check link attached to it (since she filled out her DOB incorrectly) so I thought that was the reason I received it.

**Comment by mathetos** [comment]
@dreazee -- has this improved overall or still having trouble? Can I close this issue for now?

**Comment by dreazee** [comment]
@mathetos -- everything is great with this!
