### ISSUE TITLE
Error message when resetting password

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#21]
![Screenshot_20190810-224744](https://user-images.githubusercontent.com/47679296/62830272-15c7ab00-bbc1-11e9-8ece-181e46aa4704.png)

This function was working until Monday, Aug 5th (the day of the meeting). 
Have tried to reset passwords for 3 different email addresses this week and have been receiving the same error message. The usernames already do not work.
Using my email and username works, though.

**Comment by dreazee** [comment]
This is the link being used:
https://sdrefugeetutoring.com/wp-login.php?action=lostpassword

**Comment by mathetos** [comment]
@dreazee what page did you request the password reset from? That link above is where you get redirected to AFTER requesting the password reset. 

I just tested with my own account on this page:
https://sdrefugeetutoring.com/login/

I tested both links and could not replicate the problem.
![image](https://user-images.githubusercontent.com/930724/62879921-050e5680-bce1-11e9-8e58-460490e291fc.png)

Please provide as much detail as you can so I can find the source of the problem.

**Comment by dreazee** [comment]
This is the page I am taken to after I click the lost password link from any event page without being logged in: 
https://sdrefugeetutoring.com/wp-login.php?action=lostpassword

That link was successfully working these last few months for new users until recently. It is still consistently functional for known users. (Similar to what is happening with the Orientation RSVP's)

I just tried one of the emails for a user account that I have been trying to reset all week... And it works! If I come across another, I will notify so you can try to figure out the source of the issue.

**Comment by dreazee** [comment]
@mathetos --Please see above... 
This seems to be acting up again. I have had to reset multiple people's passwords over the last few days since they are getting the above screenshotted error message again. They are receiving this error message after using the link in the ""now able to RSVP" email: https://sdrefugeetutoring.com/wp-login.php

Which is strange since I am able to do it FOR THEM using that lost password link on the "wp-login" page which is: https://sdrefugeetutoring.com/wp-login.php?action=lostpassword

But they are unable to do it for themselves... Which is a real humdinger

**Comment by dreazee** [comment]
@mathetos --  I've been receiving SO MANY emails of people getting this error message. UPDATE: I am sometimes able to use the link to reset for them, and sometimes it doesn't work. I've spent hours and hours dealing with emails over the last few days. 😬

**Comment by mathetos** [comment]
Sorry this fell off my radar. I'll look into it very soon.

**Comment by mathetos** [comment]
OK, I've updated the EVENT reset password link to point here:
https://sdrefugeetutoring.com/login/lost-password/

I tested that form and it works as intended. So all should go fine now. Please re-open this if there's more problems.

**Comment by dreazee** [comment]
@mathetos this is still an issue. Can not forgot out how to re-open case

**Comment by mathetos** [comment]
@dreazee I need to know the exact steps you're taking to recreate this issue, because I've tested it many different ways and cannot create a problem with this at all. 

This is what I'm doing:

1. Go to this page: https://sdrefugeetutoring.com/login/
2. Click on the "Lost password?" link in the login box
2.b. I also test clicking on the "Click here to restore it." link, both options have the same next results. 
3. Insert my email address. 
4. Get this success message:
![image](https://user-images.githubusercontent.com/930724/73504677-0a418980-4385-11ea-9d94-f89707582b8a.png)

5. Click through the link that is sent in the email, and the password is reset correctly.
