### ISSUE TITLE
Fix: Update Welcome Emails to reflect new time commitment, plus other edits

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#22]
--"You can now RSVP for Refugee Tutoring Sessions!" email: 
1. Update time commitment (changed from 3 times a month to "once a week while tutoring is in session") 
2. Remove this line: "Your password was emailed to you when you filled out your registration form. If you have lost that, feel free to"; 
Replace with: "Please"
We do not email a password so this is confusing.
3. Add link to "our calendar" : https://sdrefugeetutoring.com/events/

--SDRT: Next Steps in your Registration process email:
1. Number 4 needs to be updated: remove "THREE tutoring sessions a month" add "ONCE a week while tutoring is in session".

**Comment by dreazee** [comment]
EDIT: The time commitment text should read "at least once a week over the course of our 7-month Tutoring year."

**Comment by mathetos** [comment]
Thanks @dreazee 

I made the change to the "Next Steps" email.

Regarding the "You can now RSVP for Refugee Tutoring Sessions!" -- just to confirm, here's the email with the updates you're suggesting. Please approve it or give me the whole text with your edits:


> Dear {first_name},
> 
> Congratulations! We received an all clear on your background check. Thank you for taking that time and effort. Background checks ensure that our students are always in safe hands.
> 
> We would love to have you begin volunteering as soon as possible. Please go to <a href="https://sdrefugeetutoring.com/events">our Calendar</a> to find the upcoming tutoring sessions that you are now eligible to RSVP for.
> 
> <strong>NOTE:</strong> You must login in order to RSVP for tutoring sessions. This ensures that only those who have passed background checks can tutor. Please login to your account by setting your password here: {lost_password_link}.
> 
> Lastly, in order for our students to receive the dedicated attention they need and deserve, we ask all volunteers to RSVP for at least once a week over the course of our 7-month Tutoring year.
> 
> Thank you again for your generosity in volunteering your valuable time for the benefit of our refugee students. We could not do this without you.
> 
> Sincerely,<br />
> <strong><em>Your SD Refugee Tutoring Leadership Team</em></strong>
```

**Comment by dreazee** [comment]
Thanks @mathetos 
Grammar fix in the next to last paragraph before the closing.

Dear {first_name},

Congratulations! We received an all clear on your background check. Thank you for taking that time and effort. Background checks ensure that our students are always in safe hands.

We would love to have you begin volunteering as soon as possible. Please go to our Calendar to find the upcoming tutoring sessions that you are now eligible to RSVP for.

NOTE: You must login in order to RSVP for tutoring sessions. This ensures that only those who have passed background checks can tutor. Please login to your account by setting your password here: {lost_password_link}.

Lastly, in order for our students to receive the dedicated attention they need and deserve, we ask all volunteers to RSVP at least once a week over the course of our 7-month Tutoring year.

Thank you again for your generosity in volunteering your valuable time for the benefit of our refugee students. We could not do this without you.

Sincerely,

Your SD Refugee Tutoring Leadership Team

**Comment by mathetos** [comment]
Thank you! This is done!
