### ISSUE TITLE
Fix: Update Caldera Form: Registration Form for Minors

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#23]
First paragraph currently reads:
"Thank you for your interest in volunteering with SD Refugee Tutoring. Please submit the following information so we can process your registration."

Change to:
"Thank you for your interest in volunteering with SD Refugee Tutoring. Please submit the following information; we will process your registration after you attend a New Tutor Orientation. The next Orientation dates can be found in Step One here: https://sdrefugeetutoring.com/volunteer/ "

**Comment by mathetos** [comment]
This is done, please review. I'll close for now but let me know if you see anything missing.
