### ISSUE TITLE
Fix: News Page not reflecting MailChimp newsletters since Sept 2nd

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#24]
@mathetos -- Went to find the link to the most current newsletter and found that they haven't been populating (is that the correct word to use here??) on our news page again https://sdrefugeetutoring.com/news/

**Comment by mathetos** [comment]
Melissa knows how to fix this, and additionally we'll be retiring the MailChimp feed once the new site is live. I'm hoping to push it live very soon. So I'm closing this for now.
