### ISSUE TITLE
Change "Reply to" on emails sent to info@ account from website Contact Form

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#26]
Please reference closed case #19  - all details are there. 
This is still an issue but am unable to re-open case #19 since I did not close it.

**Comment by mathetos** [comment]
I tested this again and confirmed again that it is setup correctly. I also reviewed our email log and you can see here that the "Reply-to" is correct:
![image](https://user-images.githubusercontent.com/930724/87487554-d5538700-c5f2-11ea-8295-fe6ab226de8e.png)

But I checked the email itself in Gmail and hitting "Reply" it goes to "SDRT Info" -- I believe the reason yours shows my name is that somehow that email address got associated with my name in your Contacts. You can see here, when I hit reply, it says "SDRT" and I believe if you click on my name in that reply, you'll see that the email address is "info@sdrefugeetutoring.com" not my email address. 
![image](https://user-images.githubusercontent.com/930724/87487665-1ea3d680-c5f3-11ea-9176-0b66a84f07af.png)

I don't believe I can resolve this issue currently, so you and Melissa will just have to stay vigilant for now in making sure you update the Reply-to each time unfortunately. I'll leave this issue open so I can continue to keep it in mind going forward.

**Comment by dreazee** [comment]
@mathetos @JasonTheAdams What is a workaround for this? If people reply to any of the multiple emails sent to them during the registration process, it will get sent to matt@sdrefugeetutoring.com and not info@sdrefugeetutoring.com (E. V. Hepworth is my pseudonym, btw!)
![Screenshot (32)](https://user-images.githubusercontent.com/47679296/128255500-474d6c68-79b6-4f5f-b9f5-6bb7c931f2f9.png)

**Comment by JasonTheAdams** [comment]
I believe I found the source of this. The Zoho Mail settings in WordPress still have the matt@ email. Unfortunately, I don't have Zoho Mail access, so I've reached out to @mathetos for aid.

**Comment by JasonTheAdams** [comment]
@dreazee Just resolved this with Matt! Please test this out and let me know if you still see this happening!

**Comment by dreazee** [comment]
This is great that the SENDER address was changed from matt@ to info@. YAY. 
Their was another issue attached to this, though, was to have the "REPLY TO" email address be the email address that was entered into the contact form. Is there a way to reopen case #19 ?

**Comment by JasonTheAdams** [comment]
Can you shoot me an example email that has the correct sender but incorrect Reply To? I'm not seeing that set anywhere that would deviate from the sending email.

**Comment by dreazee** [comment]
There isn't a separate "reply to" field, so when I hit reply, the email goes to info@ which is the sender
![image](https://user-images.githubusercontent.com/47679296/134939459-4fe6f46b-033b-4711-9878-311f3a2bca11.png)
