### ISSUE TITLE
Re: Newsletter sign-up on Website

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#27]
1. Change Newsletter Action Button on [caldera_form id="CF5b7c91a96af4b"] from "Send Message" to "Subscribe". 

2. Currently, the "Get SDRT News in Your Inbox" right side panel does not show up on mobile on: https://sdrefugeetutoring.com/news/  Can the website be adjusted so the Newsletter Sign Up form shows up on the News page on a mobile device?

**Comment by mathetos** [comment]
Good catch! Fixed!
![image](https://user-images.githubusercontent.com/930724/87487907-c4574580-c5f3-11ea-8fb8-c022243853a8.png)
