### ISSUE TITLE
[HIGH PRIORITY] Tracking system/report for Event Attendance 

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#28]
- Currently there is only a way to track rsvps, not actual attendance, so we don’t have accurate counts when we export everyone’s data. 

- We would like a way to make an Attendance Report with parameters for a specific date period but also for a specific user.

**Comment by mathetos** [comment]
The way we want to address this one is via the "Tools > Export" option. So in essence, by doing that, we'll also address Issue https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/42 

We're essentially enhancing the Export tool to be able to do the following:

1. Limit the date-range of the RSVPs being exported according to the EVENT DATE
2. Choose which fields to export from a short list: Name, Email, Attended (Yes/No), Event Date, Date of RSVP

The "Posts" export has options like that. We want to add those kinds of options to the "RSVP" export
![image](https://user-images.githubusercontent.com/930724/107605842-2f4c1780-6be9-11eb-895c-214fe3344c60.png)

**Comment by JasonTheAdams** [comment]
For the filters:
- Have start and end date fields that default as today 30 days ago
