### ISSUE TITLE
[HIGH]  Auto email re: no-show to all Tutoring Date events

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#29]
- Currently an email is sent out manually when someone RSVPs but does not check-in (red x instead of a green check mark)

- For any Event Category = Tutoring Dates, we would like an automatic email to be sent to all users who have RSVP'd to a Tutoring Date Event but did not check-in.

- Automatic no-show emails get sent ONLY to those non-attendees of an event where the Event Category = Tutoring Dates and only after the Tutoring Date event End Time.

- Perhaps this would look like an action button on the event page that is accessible only to someone with a "Volunteer Registrar" role. This button on the event page could be pressed and anyone who has not attended the session will be sent out a specific "NO-SHOW email".

- We will provide the specific "no-show email" to use, just let us know!

**Comment by mathetos** [comment]
Triggering auto-emails can be disastrous sometimes, so we should do this carefully. I think it's better if we trigger them individually but I can do it in a way that doesn't take much time. 

I think it would look similar to this, an email icon that only appears when they did NOT attend:
![image](https://user-images.githubusercontent.com/930724/87489942-2e261e00-c5f9-11ea-8221-96704dfdf3aa.png)

You can click on that after the event, the page would refresh and it would then look different somehow (maybe a checkmark next to it) to show that the email was sent. You'd do this individually for each no-show. 

If you think that will work, here's what would have to happen from a code perspective:

1. Add the column to the RSVP list on the event pages
2. Add the logic for the email to be triggered when that icon is clicked. 
3. Add the text of the email to the "RSVPs > Email Settings" screen so it can be easily updated in the future. 
4. Add the logic for the email icon to appear differently after it's been clicked. 

Let me know how that sounds.

**Comment by dreazee** [comment]
@mathetos That sounds great! Much faster than previously and then I would know the emails were actually being sent. HOWEVER, I do not have access to a "RSVPs> Email Settings" screen. You are able to update this permission? Seems like there's a lot of fun stuff I don't have access to!

**Comment by JasonTheAdams** [comment]
@mathetos @dreazee I'm working on this now. What would you like the email subject to be? Something like "We missed you at {event name}"?

**Comment by dreazee** [comment]
@JasonTheAdams @mathetos  For the sake of brevity, it could just be "We Missed You!" Our event names are usually pretty detailed.

**Comment by JasonTheAdams** [comment]
Great! Thank you!
