### ISSUE TITLE
[VERY HIGH] Embed Code of Conduct on website & linked to User Account

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#30]
1. We want users to agree to the code of conduct on THEIR USER ACCOUNT and have that agreement linked to their user account. (we do not want posted to the public on the website)
2. The system would not allow a user to RSVP unless they have agreed to the code of conduct.  

Am getting clarification on exactly the functionality that is desired with this issue so will edit this text if necessary.

**Comment by mathetos** [comment]
@dreazee Can you provide me a link to the Code of Conduct text so I can implement it on the website? I'm not sure where that is at at all.

**Comment by dreazee** [comment]
@mathetos EDIT: we would want the Code of Conduct to be embedded into their account to agree with a check mark or something of the sort, not necessarily posted to the public on the website. 
Code of Conduct available here: https://drive.google.com/file/d/0Bwq1yVR39RMuV3phbTA4WG1PNTR0V3hONzlHNTRvLURmd05v/view?usp=sharing
