### ISSUE TITLE
[VERY HIGH] Add an Orientation/Refresher requirement to a User Account

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#32]
- Related to issues #30 and #31 -- an "Orientation/Refresher" entry would be added to a USER ACCOUNT that needs to be satisfied before a user is able to RSVP. Similar to how a user "Role" needs to be "Volunteer" or 'Volunteer Minor".

- Since not everyone has registered yet upon attendance of an Orientation, this entry would be best to be in the form of a box that needs to be manually checked by the Volunteer Coordinator upon attendance of an Orientation and completion of registration.

**Comment by mathetos** [comment]
I think the easiest way to implement this would be to add a new field on the user profile page that looks like this:

![image](https://user-images.githubusercontent.com/930724/87489308-9411a600-c5f7-11ea-8470-496659e1aed3.png)

This is how you would do it:
1. Go to "Users > All Users"
2. Search for the volunteer by name or email address
3. Click to edit the user
4. Go to the Orientation field toward the bottom of their profile and update the option
5. Click Save.

Then they would get the email saying they can now RSVP successfully. 

If that works, then here's all the things that need to be updated from a code perspective:

1. Add the new user field and user "meta" data
2. Update the RSVP functionality to require that the orientation meta be set to `true`
3. Change the auto-generated email to the volunteer to NOT be sent when their background check clears
4. Trigger the auto-generated email to the volunteer AFTER their orientation option is saved to "yes"

Does that sound right, Andrea?

**Comment by dreazee** [comment]
@mathetos This sounds like a great start. However, let's talk more about the auto-generated emails. Many times an Orientation attendance would be recorded BEFORE a background check is completed. 
So an auto-generated email would be sent WHEN both these two are completed: 

1. Background check is clear 
AND 
2. After Orientation option is saved to "yes". 

So the code would need to be updated to reflect the following:

   1.  After a background check clears, an auto-generated email would be sent if Orientation meta is set to "true"/Orientation option is set to "yes"
   2. Auto-generated email would be sent after Orientation option is saved to "yes" ONLY if background check is clear/Role equals "Volunteer Minor" or "Volunteer"

Is that possible?

**Comment by dreazee** [comment]
@mathetos Currently I have ZERO access to any Volunteer Profile Information so I would not be able to implement this. I will make this a separate issue to change my permissions...

**Comment by mathetos** [comment]
Fixes via https://github.com/SDRefugeeTutoring/sdrt-custom-functions/commit/e235769b0ce6fd2e964e729a7f052a7cc1dc59f8
