### ISSUE TITLE
[MODERATE] ability to create an exportable Donations report using different parameters

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#33]
ability to create a Donations report using different parameters (time period, donor name, etc) that is then exportable in some way.

currently, there does not seem to be a way to do this.

**Comment by mathetos** [comment]
HI @dreazee 

Yes you can do this, though I need to double-check your user permissions. But here's where it would be:

1. Go to "Donations > Tools"
![image](https://user-images.githubusercontent.com/930724/87488604-aee31b00-c5f5-11ea-9445-2a37637da360.png)

2. From there you'll be on the "Exports" screen. You have LOTS of donation export options there. 
![image](https://user-images.githubusercontent.com/930724/87488670-d639e800-c5f5-11ea-89a1-72232306eb1f.png)

3. Another option is to go to "Donations > Reports". From there you'll see an "Income Breakdown" section that has a button that says "Export CSV". That is a good daily breakdown as well. 
![image](https://user-images.githubusercontent.com/930724/87488770-0b463a80-c5f6-11ea-81bd-c836def44460.png)

Please review them in detail and let me know if you need something different
