### ISSUE TITLE
[HIGH PRIORITY] Create a "Who We Are" page under the "About Us" menu that lists Board Members

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#34]
The board members need to be listed on website for businesses and grants and foundations to legitimize SDRT. 
Pics not necessary but could be there, too

**Comment by dreazee** [comment]
@JasonTheAdams  This is a NEED and will be added to our website projects list. I am collecting the bios and photos this month.

**Comment by JasonTheAdams** [comment]
@dreazee Were you able to getter the bios and photos?

**Comment by dreazee** [comment]
@JasonTheAdams Nope! Thanks for checking back on this but we're still working on collecting those. I am making the Staff/Board folder in the shared drive and will share that with you when it is completed.

**Comment by dreazee** [comment]
@JasonTheAdams I just shared you on the SDRT shared drive for the Bio/Staff photos.  There's still a few to grab but the folders are there, just empty.
The entire "About Us" needs to be expanded. We need 3 more subheadings - 
1. Our Mission
2. Team 
3. Board of Directors
and THEN 
4. Contact

EDIT: Actually, we might add another submenu - between Our Mission & Team. A "Who We Are" - or something like that which is just a copy of the About Us page (with the idea that not many people actually click that main menu heading) I actually always forget that information actually lives there.
