### ISSUE TITLE
[VERY HIGH] Error using Email sign-up on website

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#35]
Received an email today that alerted of issue with an error message while trying to sign up for Newsletter on website. Screenshot included in the email:
![Screenshot_20200715-124005](https://user-images.githubusercontent.com/47679296/87596059-54ed5e80-c6a4-11ea-9b72-6cdf5b482886.png)

Tried to sign up using the website newsletter sign-up form myself and this was the error message received:
![Screenshot_20200715-123738](https://user-images.githubusercontent.com/47679296/87596216-9a119080-c6a4-11ea-84df-a20c2efaa6c6.png)

**Comment by mathetos** [comment]
Thanks, this is resolved. Please email Shimona to see if she can confirm it's fixed for her as well. Thanks!

**Comment by dreazee** [comment]
@mathetos Eek! The email sign-up form is still not working on my mobile using a Chrome browser. I tried to sign up on a Firebox browser, though, and it worked fine. Still getting the same error message as above.
![Screenshot_20200717-093141](https://user-images.githubusercontent.com/47679296/87809658-99960880-c810-11ea-9ffb-eb8100d8fd0a.png)
