### ISSUE TITLE
[VERY HIGH] Embed Volunteer Release into User Account; agreement a requirement to RSVP

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#36]
Similar to #30 --

1) We want volunteers to agree the Volunteer Release online and have that agreement linked to their user account. (we do not necessarily want posted to the public on the website)
2) This would be one of the requirements in order to RSVP; the system would not allow a user to RSVP unless they have agreed to the Volunteer Release.

Volunteer Release can be found here: https://drive.google.com/file/d/0Bwq1yVR39RMuVjZIWkhKalNoalBKbGhKNnE1WWJBeVhSeGVv/view?usp=sharing

**Comment by mathetos** [comment]
Fixed via https://github.com/SDRefugeeTutoring/sdrt-custom-functions/commit/e235769b0ce6fd2e964e729a7f052a7cc1dc59f8
