### ISSUE TITLE
Remove or change auto-email after submitting newsletter sign-up

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#37]
Currently, a "thank you for contacting us" email is sent to people after signing up for Newsletter. This is very confusing and needs to either be stopped or changed. 

If changed, it would need to read with a subject line: "You are now subscribed!"  And a body that starts with: "Thank you for subscribing to the SDRT newsletter." 

Currently what is sent out looks like this:
![Screenshot_20200722-105703](https://user-images.githubusercontent.com/47679296/88211634-d3994d00-cc0a-11ea-8bfb-c8f654857533.png)

**Comment by JasonTheAdams** [comment]
@dreazee Is this still happening now that we've switched to Gravity Forms? I'm honestly a bit confused as to how that would happen. It's not using Caldera Forms (or Gravity Forms) in any way, but is a direct integration with Mailchimp. It's possible, therefore, that Mailchimp is sending out the email, but that would be odd.

**Comment by dreazee** [comment]
@JasonTheAdams  Sorry it took me a while to get to this! So, yes, this is still happening; I just tested it out. The confirmation email is in the Caldera Forms template, so I'm thinking it is a Caldera Forms integration through Mailchimp and needs to be removed on the Mailchimp side. I will make time to look into this on Mailchimp next week; I just need to confirm login info with Melissa.

**Comment by dreazee** [comment]
@JasonTheAdams I tested this again

**Comment by dreazee** [comment]
@JasonTheAdams I tested this again and there now seems to be only automated emails from Mailchimp being sent and not the above Caldera forms-looking auto message.
