### ISSUE TITLE
[VERY HIGH] STILL ERROR W/ EMAIL SIGN-UP 

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#38]
Please refer to #35 – this problem still an issue.
Email sign-up on website is not operational again on both Chrome and Firefox browsers. Received same message using both browsers:
![Screenshot_20200722-201735](https://user-images.githubusercontent.com/47679296/88316025-03f4f000-cccc-11ea-8fff-0366c4279752.png)

@mathetos Here is the email, sent yesterday, that brought this to my attention again:
![Screenshot_20200723-093610](https://user-images.githubusercontent.com/47679296/88316111-271f9f80-cccc-11ea-9899-83a7c1721e6f.png)

**Comment by mathetos** [comment]
I looked into this more today, ran some plugin updates. It's still being problematic. I need to copy the site locally to debug it. I'm working on a new workflow to be able to do that a lot more effectively now so this type of thing is easier going forward. I'll keep you posted on my progress.

**Comment by dreazee** [comment]
Issue seems to be resolved

**Comment by dreazee** [comment]
Issue seems to be resolved
