### ISSUE TITLE
[VERY HIGH] Existing User able to Request New Checkr Background Check so Linked to their User Account

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#39]
1. As of now, there is nothing in place where an existing SDRT User can request a personalized background check from Checkr so that their User Account Role will automatically update from "Volunteer Pending" to "Volunteer" when their background check clears. Thinking this would look like the Existing User being able to start a new background check from Profile page. 

2. In the past we have sent Returning Tutors/Existing Users a SDRT general Checkr link, not something that is specifically linked to their account. Whether an Existing Tutor had completed a new yearly background check was kept track of manually.

**Comment by mathetos** [comment]
I'll make this a priority right away.

**Comment by JasonTheAdams** [comment]
### Dev Notes:

**Resolve issue wherein Checkr link did not get attached to user**
As described in #13, the admin sees the user does not have Checkr details, clicks a "Request new Background Check" button, and then the details are attached to the user. Checkr will email the user and the admin will take it from here. The button should _only show up_ when the Checkr details are mising.

**User Requests new Background Check after it's annually cleared**
The ideal flow for a user getting a new background check will be to go to their profile page and then click a button in the "Background Check" section which retrieves a new link from Checkr for them to use.

**Annually Clear Background Checks**
Potentially as a part of this, or another Issue, once a year the background check status of all volunteers (volunteer role) needs to be cleared. A bash action on the users screen would work. This is only visible to admins and SDRT Leadership (role).

**Comment by dreazee** [comment]
@JasonTheAdams @mathetos  EDIT: I see this was mentioned in the Dev Notes as "Resolve issue wherein Checkr link did not get attached to user" 
ORIGINAL: It would seem that some User's Checkr "Candidate ID" is missing from their profile so they are given an error message when requesting a new background check. How do we find that information in Checkr? I am unable to see it in their profile in Checkr. It would be great for me to be able to manually fill in their Candidate ID from their previous background check so that they can use this "Request Background Check" functionality.

**Comment by JasonTheAdams** [comment]
@dreazee Ok, great. Just to be clear, does that resolve the issue? Or is there a scenario not currently being handled?

**Comment by dreazee** [comment]
Sorry to confuse @JasonTheAdams When the above scenario happens, we get an error message on our end that there is no birth date or something. We are unable to request a background check using the "Request new Background Check" button. Hence wanting to know where I can find the a User's "Candidate ID" in the Checkr portal. I am thinking perhaps the functionality attached to my info@ account was limited when @mathetos set it up and maybe there is an admin@ account that has full acccess... ?

EDIT: Here's a photo of the error message!
![image](https://user-images.githubusercontent.com/47679296/134442158-f9ea2b1b-8c51-43d6-8aa8-c7a4d6bd6fad.png)

**Comment by JasonTheAdams** [comment]
@dreazee Hmm, interesting. So the way that button works is that it attempts to create a new information with the data available. So if the user has an associated Candidate ID, then it uses that. The user's birthday is only required if the user does not have a Candidate ID. If they don't have their birthday entered, then they have registered at some old point? The birthday isn't cleared at any point for users, so if they entered it once it should remain.

I could add a field for the admin/user to be able to add their birthday for an existing account.

As far as Checkr access, I'm afraid you have more access than I do. I'll see if Matt can get me admin access.

**Comment by dreazee** [comment]
@JasonTheAdams @mathetos I'm not sure that adding that field would help. but if that's east to do I could test that out to see if that would be a fix!... An easier fix would be if I can get access to a User's Candidate ID—that would solve everything. And yes, these might be people who have volunteered with us quite a while ago...
