### ISSUE TITLE
[VERY HIGH] Change Andrea Zeidell's User Account permissions to acces "Volunteer Profile Info"

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#40]
Needs to have access to any User's "Volunteer Profile Info" in order to implement "Orientation Attendance" requirement laid out in Issue #32 
Also, having access to a User's "Background Check on File" section would allow to be able to accurately update a User's account to include receipt of a Cleared background check results when it does not happen automatically thru Checkr (a common glitch).

**Comment by mathetos** [comment]
Fixed via https://github.com/SDRefugeeTutoring/sdrt-custom-functions/commit/e235769b0ce6fd2e964e729a7f052a7cc1dc59f8
