### ISSUE TITLE
[HIGH PRIORITY] Export the RSVP data (name and email) from a specific event into a .csv file

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#42]
Currently there is a "Print RSVPs" functionality on the event page (where I can then save as a PDF) but the "Attended" and "Actions" columns i also get pulled into the document, as well. 
I'm looking for a way to export just the RSVP name/emails to be used in a separate document each tutoring session, with the ability to them just copy the emails, if needed. So a .csv file would work perfectly. 
We will be using this information to pair students with RSVP'd tutors 24 hours in advance or to easily be able to copy all the emails from an event to send a mass email, etc

**Comment by mathetos** [comment]
Closing in favor of #28 -- this will get addressed in that work.
