### ISSUE TITLE
[HIGH!] Change "Welcome" Email for Newsletter Subscribers

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#45]
The Email people receive after signing up to the newsletter is a bit... confusing. It seems to be the same form used after submitting a question on the website? That would be great to change this! Please see screenshot below for details. 
![Screenshot (3)](https://user-images.githubusercontent.com/47679296/105086271-aa3c6b00-5a4d-11eb-8a20-80f0f512e26b.png)

**Comment by dreazee** [comment]
Looks like I had already submitted this back in July! #37

**Comment by JasonTheAdams** [comment]
Closing this as a duplicate of #37
