### ISSUE TITLE
LOGIN ISSUE 

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#49]
Still getting at least one login issue a week. Brought it up in Slack in January but never followed up since it's been so hectic.

This specifically from cwmeyer93@gmail.com "I tried to login, but my password wasn't recognized. Then when I tried the [password] reset, that wasn't recognizing me." 
Last week the issue was with stephen.j.gilmour@gmail.com - same problem.

Issue seems to be when someone is logging in from a mobile device from an event page. I tell them to refresh the page and sign in from:
https://sdrefugeetutoring.com/my-profile/ And that works.
One of the error messages looks like this:
"Failed security check, expired Activation Link due to duplication or date."
It's happened to me a few times when trying to login on my phone and directly through an RSVP event page.
Another error message from trying to login from an event page using a mobile device is the following:
{"success":false,"data":{"html":"<div class=\" alert alert-error\">Submission rejected, token invalid<\/div>","headers_sent":false}}

@mathetos @JasonTheAdams

**Comment by JasonTheAdams** [comment]
Looks like this has something to do with Caldera Forms. @mathetos mentioned that in the not too distant future we'll want to migrate away from Caldera Forms since it is [going to be sunset](https://calderaforms.com/2021/03/the-future-of-caldera-forms/) on December 31st, 2021. I strongly suspect this issue will be resolved during the process of adopting a new form plugin.

Matt, if you feel like we should tackle this before then let me know. As you know, bugs of this nature (sporadic and having to do with authentication) can be tricky to nail down.

**Comment by dreazee** [comment]
@JasonTheAdams Thanks for the explanation on this. Our last tutoring session before before Summer Break is June 3, so fixing this sounds like it wouldn't be the best use of time. @mathetos I vote to just leave it, then, since the issue is handled easily via a quick email to the User experiencing the issue.

Would we be able to aim for an alternative to Caldera Forms to be adopted before mid-August? That is when we start ramping up Volunteer registrations and Users start logging in again in anticipation for the start of the new school year.

**Comment by mathetos** [comment]
@dreazee Yes, our plan is to migrate to the new form plugin as soon as the latest batch of background check and volunteer issues are fully shipped and on the live site. I'd venture to say it should be done in June or July at the latest.

**Comment by dreazee** [comment]
@mathetos Awesome! Thanks for the update.

**Comment by dreazee** [comment]
@JasonTheAdams  Hi Jason. This is still an issue as people try to RSVP for our Aug 21 event. It is the end of July and it still doesn't look like we have migrated to the new form plugin as Matt referenced in the last comment on April 26. How can we proceed with fixing this asap?

**Comment by JasonTheAdams** [comment]
@dreazee Matt and I just tested this out. It was logging the user in, but sending them to an unexpected new page. I just made a change so, when you log in, it keeps you on the same page as the event page you logged in from. Can you please test this out and let us know if it resolves the issue? 😃

**Comment by dreazee** [comment]
@JasonTheAdams  I just tested it by logging in on an event page from my mobile phone (which NEVER worked previously), and it worked! YAY!
