### ISSUE TITLE
[VERY HIGH] Unable to Login from Login link!

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#53]
@JasonTheAdams  Another login issue is upon us! 
When trying to login from the Login page, it produces an error message (credentials unable to be verified or something) : https://sdrefugeetutoring.com/login/ 
However, logging in with those same credentials (username & password) on the My Profile page works: https://sdrefugeetutoring.com/my-profile/

**Comment by JasonTheAdams** [comment]
@dreazee and I spoke in Slack and determined the login page is just problematic right now — and the user can login from their profile — so I just removed the login page from the main navigation. This issue will likely be fully resolved after we make the switch off of Caldera Forms.
