### ISSUE TITLE
FIX: Day-before Reminder Email not being sent

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#55]
Hey @JasonTheAdams Tested out the Reminder Email function on a Hidden Test event I made and I never received an email. Did this a few times, changing the date/time each time and NOTHING. 
https://sdrefugeetutoring.com/event/mshs-tutoring-test/

**Comment by JasonTheAdams** [comment]
@dreazee I'm embarrassed to admit this, but I'm realizing that I wrote the code to send the emails the day before... but I forgot to schedule the event to run every day... 🤦‍♂️

I apologize for the mistake. It's set up now and ran for the first time. It will run every evening and send notifications for events coming up the following day. Should the events run in the morning, perhaps? That would give folks that day to find the reminder in their email. 🤔

**Comment by dreazee** [comment]
D'OH! Yes, definitely set it up to run in the morning, so they get that email at least 24 hours in advance. Thanks!!
