### ISSUE TITLE
[MEGA HIGH PRIORITY] USER RECEIVING RSVP PROMPT ON EVENT PAGE AFTER SUBMITTING RSVP (USER IS ABLE TO RSVP AGAIN)

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#57]
ahhhhhhhhh @JasonTheAdams the website broke itself again! A User (in this case Andrew Hayhurst) is receiving the RSVP prompt on an event page—e.x. Hi Andrew! Do you plan to attend this Tutoring session?—even after they have submitted an RSVP. There should be a nice message saying "Thank you for your RSVP. If you need to cancel please email info@sdrefugeetutoring.com" or something - I don't remember exactly. Instead of this Thank You message, users are able to double and triple RSVP.

![image](https://user-images.githubusercontent.com/47679296/134942922-dea05c5a-a4c0-4b4f-8efc-46e2b602105c.png)

**Comment by JasonTheAdams** [comment]
Ok, we're nailing this down. In the future, I'd like to completely refactor how this section works as it's really a [finite state machine](https://en.wikipedia.org/wiki/Finite-state_machine) and the way it's been reflected in the code is too easily jumbled based on the many conditions.
