### ISSUE TITLE
[HIGH-HIGH] Change "from" email address on NEW RSVP alert email from info@ to admin@

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#58]
Soooooo, @JasonTheAdams  ...the NEW RSVP alert emails "From" field needs to be changed to something else besides info@
 I forgot about what a mess info@'s sent folder becomes when EVERY email is changed to be sent from info@. Specifically, we need to change this specific email to be sent by matt@ or admin@ or SOMETHING else besides info@. I believe that info@ is the only account that receives these emails alerts so a user would not be able to reply to the email. 
Really sorry about this!
**EDIT: To be clear, we still need these alert emails to be emailed out to info@ as I need to look over every RSVP as it rolls in, but I just want the "from" field to be changed so that my "Sent" Mail Folder isn't clogged with at least 180 extra emails each week.**

**Comment by JasonTheAdams** [comment]
@dreazee I'm sorry, I'm not quite following. Let me break it down and see if I'm on the right track.
- Emails should be sent FROM: admin@sdrefugeetutoring.com
- Emails should be sent TO info@sdrefugeetutoring.com AS WELL AS the intended user email

That sounds like a lot of emails going to info@, which makes me think I'm misunderstanding something.

**Comment by dreazee** [comment]
@JasonTheAdams Apologies for any confusion.
We're only talking about the "New RSVP" alert emails. **EDIT:: We are also talking about "SDRT: A new volunteer just registered" and "SDRT: Registration form for Minors" emails, too!!**

I had thought that the "New RSVP" alert emails were only sent to info@ for my use and are not sent to the user who RSVP'd. BUT from the content of the email it looks like these are supposed to be sent to the User, as well, but that functionality of the "New RSVP" alert being sent to the user has never worked! So let's make that work so that the User has a record of the sessions they have RSVP'd to!! THIS IS GREAT.

So yes, the #1 and #2 parameter listed above is what is desired.

With that #2 parameter in mind, we would need to have the "from" email address on the "New RSVP" alert emails be an email address that would be checked by me in case someone responds to it. 
Would we be able to create an entirely different Zoho @sdrefugeetutoring.com email address like rsvp@ that these "New RSVP" emails could be sent 'from' that I would have access to? OR we would need to give me access to the admin@ email account.

And yes, it's a lot of emails going to info@ but it's necessary for me to monitor RSVP's as they come thru and it helps me track user RSVPs thru Gmail which is much easier and useful on a day-to-day basis than thru the backend of the website. When the emails were "sent" from matt@ (see below), the emails were grouped together each day by event date so it doesn't seem like so many emails.

Previous:
![Screenshot_20210927-215702](https://user-images.githubusercontent.com/47679296/135026991-95d3c718-e395-480a-b333-d59aa1334772.png)

Now:
![Screenshot_20210927-215751](https://user-images.githubusercontent.com/47679296/135027023-77ea5dea-5dc1-4e19-b40b-9dcc40c112f9.png)

**Comment by JasonTheAdams** [comment]
@dreazee I updated the FROM email to be admin@sdrefugeetutoring.com. As for the rest, I'd like to hop on a call in the next couple days to make sure we're on the same page.

**Comment by dreazee** [comment]
@JasonTheAdams !! Did you updated the TO email, also????? Since this change was made, info@ is no longer receiving the VERY IMPORTANT RSVP emails!

**Comment by JasonTheAdams** [comment]
@dreazee I pushed the change so all emails sent out have a Reply-To for info@sdrefugeetutoring.com. So I believe our To/From woes should we all set, there.

As far as not receiving the RSVP emails, I have not touched the To address for this. You can see the [form settings here](https://sdrefugeetutoring.com/wp-admin/admin.php?edit=CF5973adca37024&page=caldera-forms), and click on Processors, then "Auto Responder"; the Recipient Email is set to info@sdrefugeetutoring.com. I do see that there's a condition that the email only goes out if they check "Do you plan to attend?" as "Yes", but I doubt that's what you're describing.

On my local setup, I see this working as expected. So if you're still not getting the emails, something odd is happening. Please check your spam folder, too, to make sure it's not being sent there since we changed the From address.

**Comment by dreazee** [comment]
I see that the form settings look to be in order but I'm still not getting the emails so something odd is definitely happening. Nothing in my SPAM folder, either. I checked on Zoho Email Platform, to see if there was an issue with forwarding and nothing is there in the Inbox or Spam, either.
