### ISSUE TITLE
[HIGH] Give Andrea a higher level access to Checkr than what the info@ Checkr login currently has

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#59]
In reference to previously posted comment in issue #39, I need password to Checkr admin account so I can have access to Candidate ID's to tack these on to veteran Returning Tutors SDRT User Accounts.
Also, according to Checkr, there seems to be a way for SDRT to change candidate information internally when something goes awry. I am assuming there is a way to do this using the admin account. In this specific case, what is happening is that they used their "preferred name" instead of their "legal name" to start their background check and is now caught in a Checkr Customer Service black hole. Much easier for me to change their name through Checkr using the admin account.

_Originally posted by @dreazee in https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/39#issuecomment-927985309_
@JasonTheAdams @mathetos I'm not sure that adding that field would help. but if that's east to do I could test that out to see if that would be a fix!... An easier fix would be if I can get access to a User's Candidate ID—that would solve everything. And yes, these might be people who have volunteered with us quite a while ago...

**Comment by JasonTheAdams** [comment]
@JasonTheAdams I believe this is all set, correct? I've shared with you the credentials in Slack and you should have full access to Checkr.

**Comment by dreazee** [comment]
No, unfortunately. We had a conversation about it on Oct 1, 2021 and it was said that Matt was working to get admin access from Checkr. I had to scroll back in our DM conversations to refresh my memory!

**Comment by JasonTheAdams** [comment]
Really? I have both Matt's credentials and the info@ credentials. I remember giving the info@ credentials to you and making sure they have proper access. Is there something else missing?

**Comment by dreazee** [comment]
The info@ credentials is what I have been using this entire time. The functionality on that account is limited. I am unable to remember under what circumstances I have received the "you do not have access to accomplish that task" message, but the next time it happens, I can add that here.

**Comment by JasonTheAdams** [comment]
Got it. So I went to update your access... and Matt's password reset again, which means I need his help again. 🤦‍♂️

I'll let you know as soon as I get access again and am able to update your access. Hahah!

**Comment by JasonTheAdams** [comment]
@dreazee I got access to Matt's account. He made me an account (to avoid this in the future) and I've updated the info@ account to have admin access.
