### ISSUE TITLE
[HIGH-HIGH] Change delivery Email Address of Contact Form submissions with subject: "Trouble with Website"

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#60]
hey @JasonTheAdams! When Users submit contact form with the "nature of your inquiry" selected as "Trouble with Website", it is not sent to info@ email address. We need to change this. Right now these emails are probably being sent to an account that is not checked.
Pretty sure that the 3 other Contact Inquiry subjects are being delivered to info@, but please double check that, too.

**Comment by JasonTheAdams** [comment]
@dreazee I just switched the contact form over to Gravity Forms. It now sends all information to info@ no matter what the nature of the inquiry is. It also sends out a notification to the person sending the email as before.

You should have received **4** emails from me, one per inquiry type. Please confirm that you've received these. I can confirm that I received a notification to my email for each submission.

**Comment by dreazee** [comment]
GOT ALL 4 OF THEM!!! THANK YOU, JASON!!!
