### ISSUE TITLE
Pull info from "Why do you want to tutor" section on Volunteer Registration Form to populate a User Profile's "Biographical Info"

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#62]
@JasonTheAdams  Can the Volunteer Registration Gravity Forms settings be changed so that it pulls the info from the "why do you want to tutor..." section and populate it into the Wordpresss User's "Biographical Info" section under "About the User"? This was previously the case under Caldera and it is very helpful to have that info in their User Profile.
FYI - I copy/pasted  the info for User "Nikita Prasad" which is why it shows up under their profile.

![image](https://user-images.githubusercontent.com/47679296/140384809-b2c5fb96-edd0-4c02-b457-ccd630e89f87.png)

**Comment by JasonTheAdams** [comment]
All set! 👍

**Comment by dreazee** [comment]
Awesome @JasonTheAdams !!
