### ISSUE TITLE
[HIGH] FIX: Not Emailed Volunteer Registration Admin Notification if DOB is under 18 years old!

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#66]
hey @JasonTheAdams  This is a weird thing that started happening when moved to Gravity Forms. 
**BACKGROUND:** A minor is asked to fill out both the Minors Reg From AND the Volunteer Reg Form; the latter is asked so that a User Account is automatically created for them and there is a record for them in Checkr (even though a background check is not asked of them)
For some strange reason (a Checkr integration is the only thing I can think of), an Admin Notification is not being triggered (I'm assuming) for a completed Volunteer Registration Form if the DOB = under 18 years of age. I just realized this today so was able to go in manually to the specific forms and "resend" the notifications, but that is just a quick fix for now.
I'm fascinated as to the inner-workings of this, so please keep me informed!

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Hmm... that _is_ and odd one. Let me lay out some steps and you tell me if I'm understanding you:
1. Minor fills out the Minor Registration form — everything works swimmingly
2. Minor fills out the Volunteer Registration form, including their DOB which is less than 18
3. The admin notification is not received

The fact that they fill out the Minor Registration form is incidental. You seem to be focusing on the fact that apparently marking the DOB as less than 18 results in the admin notification not being sent. But if the DOB is 18 or above, it does send.

Is this correct?

**Comment by dreazee** [comment]
@JasonTheAdams  Yep, yep, and yep. That is all correct.
A Volunteer Registration admin notification is being sent if DOB is 18 or above but not being sent if DOB is under 18.

It's the oddest thing which is why I thought it might have something to do with the Checkr integration since a Checkr invite doesn't get triggered if the DOB is under 18 years of age...

**Comment by JasonTheAdams** [comment]
Yeah, that's a good thought. We _should not_ be attempting to create a Checkr candidate for the person if the volunteer is less than 18 years old, right?

If that's the case, I can see that the code isn't taking this into account. It's possible that this is preventing it from working properly. It is supposed to send an email to info@ if there's an issue with Checkr.

This whole thing did remind me that I want to get some proper error logging on the website, so I'm setting up a free https://sentry.io account. All errors will be automatically sent to that service with ridiculous amount of information to help me troubleshoot.

**Comment by dreazee** [comment]
I want a candidate ID created for everyone. This way we have a list in Checkr of all our volunteers, even minors. Plus, when our minor volunteers come of age, the task of requesting a yearly background check for them is automated by using that button in their SDRT User Account. The alternative would be to give them a general link via email which is much more work on our end.

I just want to reiterate that this a new issue when Gravity Forms was installed.

That's great about sentry.io account. Is there anything I need to do on my end for this?

**Comment by dreazee** [comment]
Hey @JasonTheAdams So this is still a thing. It just happened to the Volunteer Registration form Submitted on: 2022/03/06 at 3:31 pm by Kristin Millar (I just deleted her actual Use Account since she marked her DOB incorrectly so a Checkr entry wasn't triggered. But the form entry still exists on the backend). 
Can you see what is logged in Sentry.io at that time so that we can troubleshoot this issue?

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I'm confused by the Date of Birth:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/2024145/158512405-28782fc9-2de1-4156-8ac1-66609ae0fbc6.png">

All the other DOBs look correct and valid, so I don't think there's an issue with the form.

Looks like they put their DOB in the future. That's impressively young and wonder if they should be tutoring. 😂

**Comment by dreazee** [comment]
@JasonTheAdams ha! Yeah people have issues with that DOB entry every once in a while. ha.
There's nothing wrong with the form. This is an issue that when the Gravity Forms was installed, I do not receive the admin notification when the DOB is under 18 years of age. I am wondering why the admin notification isn't being triggered and wondering if there was any error in sentry.io that logged the problem.

**Comment by JasonTheAdams** [comment]
@dreazee I did some more digging and found a bug that was preventing the errors from reaching sentry, as well as the form from finishing up — including sending the email. The forms should now submit properly and reach your email, but I want you to be aware of what was breaking things:
1. Folks must be **16** or older to have a Candidate created on Checkr
2. Folks must be **18** or older to have an Invitation created on Checkr

It seems to me like this has always been in effect. How would you like to handle these situations? You mentioned you always want a candidate ID for each user, but it seems like this won't be the case for volunteers under 16.

**Comment by dreazee** [comment]
Super work digging @JasonTheAdams !!
Okay, great. My main concern was the form submissions not reaching my email. 

The 1st situation, I did not realize. Good to know that our older students have a candidate ID created for them.
Yes, the 2nd parameter has always been in effect, which is what is desired.

I'm not sure that either of those situations need to be handled? Maybe I'm confused by the question!
If a Candidate ID can't be created than it's really not a problem. There's not many volunteers who, after serving with us in high school, are still able to come back once they go to college! If this does happen, I can just handle manually.

**Comment by JasonTheAdams** [comment]
By "handled" I really just meant if you want to the form to do anything unique in the situations where the volunteer is too young to get a candidate and/or invitation created. But you've answered the question, so I'll go ahead and just prevent it from attempting to make the candidate/invitation based on the age to prevent errors. 👍

**Comment by JasonTheAdams** [comment]
Ok! I think I've wrapped this up with 7c7c859f! 💪

**Comment by dreazee** [comment]
> I'll go ahead and just prevent it from attempting to make the candidate/invitation based on the age to prevent errors. 👍

We still need that 2nd parameter to be in effect "Folks must be 18 or older to have an Invitation created on Checkr". It is too confusing if minors are being sent invitations to complete a background check when that is not a step they need to complete. It creates a lot more emails to SDRT and possible payment of background checks that aren't legal and necessary.
Was that changed?
