### ISSUE TITLE
[HIGH] Change Footer of Website to reflect Social Media & updated Copyright date

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#74]
@JasonTheAdams Hi Jason. Here's the official Issue, as originally discussed via DM.  Instagram & Facebook logos with links need to be added to the Footer. 
Instagram: https://www.instagram.com/sdrefugeetutoring/
Facebook: https://www.facebook.com/sandiegorefugeetutoring/
Does this live somewhere in WP that I would be able to adjust, if needed? (like if mailing address changed). 

Also, copyright needs to be updated to 2022. Can you add a script to automate this so that it updates to 2023 on January 1 and so on?

**Comment by JasonTheAdams** [comment]
I've added the social media icons and updated the copyright date. I wish I could make the date automatic, but the way it works in this theme it's fixed.

As far as updating these things yourself, can do so via the Customizer. From the admin go to Appearance > Customize in the menu. Once in the customizer go to Footer > Footer Layout to change the very bottom, and Widgets to change the content above that (i.e. address). Admittedly, it's not quite as simple as it could be, so if you want to just ask me to change it in the future that's fine, too. 😃

**Comment by dreazee** [comment]
@JasonTheAdams  I forgot to tell you that it doesn't look like I have access to this on my menu.... (see screenshot below) Will you please give me access and then let me know so I can poke around?
![Admin Menu](https://user-images.githubusercontent.com/47679296/189815556-d0bd7b8a-f9d7-4b91-b376-b009cf076056.png)
