### ISSUE TITLE
[HIGH] VOLUNTEER PORTAL: UPCOMING EVENTS - Display Portal Menu

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#77]
@JasonTheAdams  OKAY.... So here - https://sdrefugeetutoring.com/volunteer-portal/upcoming-events/
Portal Menu is not displayed on the Event page. Not sure if this is an issue because there are no tutoring events listed, but either way, the Portal Navigation Menu should definitely be displayed at all times.

**Comment by JasonTheAdams** [comment]
@dreazee Please review the video I sent on setting everything up. The Upcoming Events system is built around trimesters. Currently, when I go to Events > Trimesters there are none. For this page to work at least one trimester must be set up **and** have at least one future event assigned to that trimester.

If this is too strict, let's talk about the circumstances surrounding the issue and we'll make this work for y'all.

**Comment by dreazee** [comment]
@JasonTheAdams OOPS! Sorry, Jason. I thought the video was only in reference to the work in order to populate the past tutoring hours onto a volunteer's profile. 
Audio avenues aren't my favorite ways to take in information so when I first received it, I got about 1 minute into the video and put it aside for later when I had more time!

A question about the trimesters (which I guess is really quarters because of summer but that is events only and not tutoring):
1. Will people still see past events in the Portal for that trimester or just events that haven't happened yet? The lingo was a bit fuzzy when you were talking about the display characteristics....

**Comment by JasonTheAdams** [comment]
@dreazee No worries! I'll try to stick to text for you, but there are times where a 5-minute video is just better than writing a book. 😆

Under no circumstances will past events show up in the Upcoming Events section. Once an event has happened it will no longer show up. So when a user is viewing events to RSVP to they are limited to future events.

**Comment by dreazee** [comment]
@JasonTheAdams I will absolutely make exceptions for your videos :) And yes, writing that all out would've been way too much time. But if you have time for a very basic outline to go with the video would help me A LOT. Especially if I need to go back to the video to remind myself of information. But if that's too much, no worries. Very grateful for you laying it all out in the video. 

Okay perfect. I assumed that but wanted to double check based on what was said in the video! This is exciting!!
