### ISSUE TITLE
[SUPER HIGH] VOLUNTEER PORTAL: REQUIREMENT STATUS - Display Orientation Event Titles, Not Just Dates

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#78]
@JasonTheAdams  Under [Orientation Volunteer Requirement](https://sdrefugeetutoring.com/volunteer-portal/requirements/), Orientation Dates are currently only displayed with a date and time.
(see screenshot below).

Let's change that red DATE to be the actual Orientation name as we have different Orientations for [Returning Tutors](https://sdrefugeetutoring.com/event/2022sept20-refresher/) and [New Tutors](https://sdrefugeetutoring.com/event/2022sept20-nto-training/). The date is also included in the Orientation Title so if it makes sense to not include it here then that makes sense to me, too.

![Orientation-Status](https://user-images.githubusercontent.com/47679296/188027284-2aa22610-92d0-4f82-a14a-a6d1dc045621.png)

**Comment by JasonTheAdams** [comment]
@dreazee Sounds good. Also, I noticed none of the orientations have addresses. Are orientations always done online? If so, I'll remove the date column to make more space for the title.

**Comment by JasonTheAdams** [comment]
What do you think about this?
<img width="974" alt="image" src="https://user-images.githubusercontent.com/2024145/188344725-c37d4b07-01af-46fa-827b-dc93d6e213cf.png">

Personally, I like the idea of showing the title, but I think including the date in the title is redundant (both on the admin-side and user-facing). I think there are nicer ways to display the date than the title, so honestly I would discourage including the date in event titles.

**Comment by dreazee** [comment]
@JasonTheAdams  Looks great.
1. re: Address: Orientations are not always online, no. But displaying the address is not needed in the portal since it is displayed on the event page. As long as we're doing away with columns, **let's do away with the Organizer column, too??**
2. Date in Title - I thought about this... ...  Some history... I always add the date to the event because volunteers are CONSTANTLY signing up for the wrong date and this was an added layer to prevent that (although it still happens even though the date is BIG on the top of the event page). I can *almost* see us doing away with the date in the event title with the advent of the new Portal.  BUT from an admin side, as things are right now, it is absolutely needed. I get hundreds of RSVP notification emails (Orientation & Tutoring Dates) that I use to easily track real-time Volunteer sign-ups without having to access another platform (great when I'm on-the-go). The date shows up in the subject line of these Notification Emails (along with the User Name) so I quickly & easily see all the information needed for the sign-up that just happened. Do you have any suggestions now when taking these 2 points into consideration— the user error and the admin-side?
** One other thing to keep in mind - Things *are* a little different since since this position is only part-time... there is not the "luxury" of being in front of the computer the entire work day. I know I reply heavily on email to access information but it is the fastest and easiest way to access info while on-the-go. So until the Volunteer Coordinator position is able to be full-time, I think this also needs to be taken into account, as well.

**Comment by dreazee** [comment]
@JasonTheAdams  LOVE the way this looks in the Upcoming Events page. Let's remove "Organizer" from Tutoring Events, too, and only have it displayed for Non-Tutoring Events.  Just to confirm, we would be able to change only the Orientation display and keep the Tutoring Dates display as-is (minus the organizer)?


> @JasonTheAdams Looks great.
> 
>     1. re: Address: Orientations are not always online, no. But displaying the address is not needed in the portal since it is >displayed on the event page. As long as we're doing away with columns, **let's do away with the Organizer column, too??**
> 
>     2. Date in Title - I thought about this... ...  Some history... I always add the date to the event because volunteers are >CONSTANTLY signing up for the wrong date and this was an added layer to prevent that (although it still happens even though >the date is BIG on the top of the event page). I can _almost_ see us doing away with the date in the event title with the advent of >the new Portal.  BUT from an admin side, as things are right now, it is absolutely needed. I get hundreds of RSVP notification >emails (Orientation & Tutoring Dates) that I use to easily track real-time Volunteer sign-ups without having to access another >platform (great when I'm on-the-go). The date shows up in the subject line of these Notification Emails (along with the User >Name) so I quickly & easily see all the information needed for the sign-up that just happened. Do you have any suggestions now >when taking these 2 points into consideration— the user error and the admin-side?
>        ** One other thing to keep in mind - Things _are_ a little different since since this position is only part-time... there is not the >"luxury" of being in front of the computer the entire work day. I know I reply heavily on email to access information but it is the >fastest and easiest way to access info while on-the-go. So until the Volunteer Coordinator position is able to be full-time, I think >this also needs to be taken into account, as well.

**Comment by JasonTheAdams** [comment]
**Address**
Sounds good! I'll remove both the address and organizer columns. We'll keep it nice and simple.

**Date in Title**
You raise a good point regarding RSVP emails. I think my preference would still be to remove it from the Event title. So I've gone ahead and updated the RSVP email subjects to now include the event date! If there are any other places you need to see the date, just let me know!

Also, no worries at all with regards to being part-time. In a very real way, I am too! My goal is to make your job easier and more efficient, not harder, so I'm happy to continue to empower the flows you have. 😃

**Upcoming Events**
As strange as this may sound, it would be a bit more complicated to remove the Organizer for some event types and not others. It would also throw off the visual flow of the table when the user views all events in one go. If it doesn't hurt anything, I'd say let's just leave the Organizer. If it's blank for sessions that's fine.

That work?

**Comment by dreazee** [comment]
@JasonTheAdams 
Re: Organizer Column -- Would really love to **remove the Organizer column in Volunteer Portal for Upcoming Events**, too. It's totally not necessary. The organizer is always us (except the rare occasion which it isn't) and that information could be found on the Calendar Event page if they needed more information or if the organizer wasn't us and they wanted a contact number. I just think it will streamline the information in the Volunteer Portal instead of having an entire column showing "Melissa Phillips". 

**Date in Title**
Okay, I will start to NOT including the date in the tutoring event title... although I still have some qualms about this. It makes me VERY nervous!! haha. We will see how it goes with the new Volunteer Portal display, though... I TRUST YOU!

I tested the RSVP email but there was no date included! I poked around on the Gravity Form and inserted the date into the subject field and also added it to the body of the email. Not sure where you originally made the changes, but it works now! So the Subject now looks like this:
"RSVP: Andrea Zeidell WILL attend 09/07/2022 Middle & High School: FIRST DAY of Online Tutoring"
I also included the date into the Orientation email notification subject line, too, and will remove the dates from the event title there.

**Comment by dreazee** [comment]
@JasonTheAdams  DATE IN TITLE still needs to be fixed. In my haste I failed to realize that the date that I included in the subject line is the RSVP date! UGH. And not the EVENT date.  I am making another Issue with just this in it... 

> @JasonTheAdams 
> 
> **Date in Title** 
> I tested the RSVP email but there was no date included! I poked around on the Gravity Form and inserted the date into the subject field and also added it to the body of the email. Not sure where you originally made the changes, but it works now! So the Subject now looks like this: "RSVP: Andrea Zeidell WILL attend 09/07/2022 Middle & High School: FIRST DAY of Online Tutoring" I also included the date into the Orientation email notification subject line, too, and will remove the dates from the event title there.

**Comment by JasonTheAdams** [comment]
I've replied in the other Issue, so we'll close this out.

**Comment by dreazee** [comment]
@JasonTheAdams  But what about the following re: Organizer Column in Volunteer Portal? I think it could also be confusing information to have up front and center like that since "organizer" is a strange word to use in the cases of tutoring sessions. Plus we do have a different director for the middle/high school sessions.  

> @JasonTheAdams Re: Organizer Column -- Would really love to **remove the Organizer column in Volunteer Portal for Upcoming Events**, too. It's totally not necessary. The organizer is always us (except the rare occasion which it isn't) and that information could be found on the Calendar Event page if they needed more information or if the organizer wasn't us and they wanted a contact number. I just think it will streamline the information in the Volunteer Portal instead of having an entire column showing "Melissa Phillips".
.

**Comment by JasonTheAdams** [comment]
Ah! Yes, thank you for bringing that back up. I'm super sleepy from the conference and my brain isn't firing on all cylinders. I've gone ahead and removed the Organizers column from Upcoming Events. 👍

**Comment by dreazee** [comment]
@JasonTheAdams  THANK YOU for doing this on a Sunday when you need to be resting. I know I need to be resting and not working, either, so at least we're doing this in solidarity?? Appreciate you immensely.
