### ISSUE TITLE
[SUPER-SUPER HIGH] VOLUNTEER PORTAL: Upcoming Events Page - completely non-operational

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#79]
Hey @JasonTheAdams ! So the [Upcoming Events page ](https://sdrefugeetutoring.com/volunteer-portal/upcoming-events) is not pulling in ANY events - I tested with Events labeled as Non-Tutoring Events, Orientation Dates, AND Tutoring Dates: K-5th Grade. Some of this was previously touched upon in Issue #76 & Issue #77 which would most likely resolve with this larger issue being resolved.

**Comment by JasonTheAdams** [comment]
Please see my comment here: https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/77#issuecomment-1236452187
