### ISSUE TITLE
Send a day-before reminder email

### ISSUE THREAD

**Issue by mathetos** [SDRefugeeTutoring/sdrt-custom-functions#8]
Send an email reminder the day before an event to all RSVPs for that event. Maybe mention their ability to Cancel their RSVP if necessary based on issue #7

**Comment by dreazee** [comment]
@mathetos Also adding a link to cancel, as well.

**Comment by JasonTheAdams** [comment]
As a note, whether or not the RSVPs are sent out is determined on a per event basis. That is, the admin can decide whether or not they want day-before reminders to go out when creating an event.
