### ISSUE TITLE
[HIGH] VOLUNTEER TIME DISAPPEARS WHEN SAVED

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#80]
@JasonTheAdams In an event listing, Volunteer Time does not save properly and the time entry disappears from event listing. I was working from this entry:
https://sdrefugeetutoring.com/event/elem-tutoring-2022-10-04/

**Comment by JasonTheAdams** [comment]
Oops! Good catch! This has been resolved in f0ce53f
