### ISSUE TITLE
[HIGH] VOLUNTEER PORTAL - Upcoming Events - Intro paragraph wording needs to be corrected

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#81]
@JasonTheAdams  Intro paragraph in the Volunteer Portal  - Upcoming Events needs to be changed. 
CURRENT: These are the upcoming events which you may be filter by trimester and event type. Please review the events and RSVP as to whether you are able to attend.
NEW: These are the upcoming events which may be filtered by event type and trimester. Please review the events and RSVP if you are able to attend.

**Comment by JasonTheAdams** [comment]
@dreazee Probably nit-picky, but the new version says "RSVP if you are able to attend", which would suggest to me I _shouldn't_ RSVP _unless_ I'm able to attend?

**Comment by dreazee** [comment]
@JasonTheAdams Here's the thing... I don't want a bunch of "no" rsvps to events that people don't need to be rsvp'ing "no" to. For example, Elementary School tutors RSVP'ing "no" to the MS/HS events on both Tuesday & Thursday or Tuesday tutors RSVP "no" to Thursday dates.... It will really crowd the RSVPs section in the backend, too...  
What if we use the updated lingo and also add a 3rd line "Please only RSVP "no" to a session if that session is part of your regular weekly attendance." I actually really like this and it would clarify why we even have the "no" as an option.
What do you think?

**Comment by JasonTheAdams** [comment]
@dreazee Yeah, I can definitely appreciate what you're saying. I wanted to play around with drawing out the message of when to rsvp "no". If it's just a few lines of text users are less likely to pay attention.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2024145/189552990-0fb5893f-051c-471e-9160-3840af03cf6b.png">

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2024145/189553088-37067387-c883-4b6e-a55a-429f8fd4cf00.png">

In the second I tried to simplify the initial text to make the whole thing two scannable lines.

What do you think of this?

**Comment by dreazee** [comment]
@JasonTheAdams  Second one works great! LOVE THIS!!!

**Comment by JasonTheAdams** [comment]
Great! All set! 👍

**Comment by dreazee** [comment]
@JasonTheAdams Does it take a while to populate? I do not see the changes https://sdrefugeetutoring.com/volunteer-portal/upcoming-events/

**Comment by JasonTheAdams** [comment]
@dreazee I believe you're running into caching again. I just added the "cache busting" I was referring to which should help prevent this in the future. Please check again and let me know if it's still not working right.

**Comment by dreazee** [comment]
@JasonTheAdams AWESOME!!! LOOKS GREAT! THANK YOU!!!!
