### ISSUE TITLE
[VOLUNTEER PORTAL] Adjust Menu headings & subheadings when Volunteer Portal goes Live

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#85]
@JasonTheAdams Melissa and I went over changing the menu subheadings when Volunteer Portal (and also Board Bios & Staff Bios for live which we are still working on!) Here is the suggested Menu alterations when the Volunteer Portal goes live. Let us know if you think differently. 

VOLUNTEERS
-VOLUNTEER REGISTRATION
-VOLUNTEER PORTAL
-EVENT CALENDAR

DONORS  _(This Menu Heading will replace "ACCOUNT")_
-DONATION HISTORY
-MANAGE YOUR RECURRING DONATIONS

GIVE NOW _This Button currently says "Give"_

**Comment by JasonTheAdams** [comment]
Yes! This is an excellent menu structure. Well done! 👍

**Comment by dreazee** [comment]
@JasonTheAdams After that Cancel button is "fixed" (hehehehe. thank you again for your honesty with this. I'm still laughing about it) CAN WE TAKE THIS LIVE??????  [EDIT: ARE WE READY?!?!?! As a now QA expert (lol), I think we're ready!!!]
We have another Orientation tomorrow, Sep 20, and it would be amazing to have this navigable from the website!! I've already heard great responses from our Returning Tutors about it.

**Comment by JasonTheAdams** [comment]
Alright, we're live! 🎉

I left "Code of Conduct" and "Volunteer Waiver" in the "Volunteers" menu. Would you like me to remove this?

**Comment by dreazee** [comment]
WOOOO!

I would like to remove them so the menu looks cleaner but still want to make those readily available. What about linking them in the [Volunteer Requirements page](https://sdrefugeetutoring.com/volunteer-portal/requirements) under the appropriate heading? When the Requirement is satisfied (turns to green), have a message displayed:
"Thank you for taking care of this! To reference this in the future, please go here." And the "go here" would be hyperlinked to the respective form.

**Comment by JasonTheAdams** [comment]
That's a good idea! Resolved in 68440e9

**Comment by dreazee** [comment]
Thanks @JasonTheAdams . But let's spiff up the grammar & wording a bit? See below:
**Code of Conduct:**
To reference this in the future, visit the [Code of Conduct page.](https://sdrefugeetutoring.com/volunteer/code-of-conduct/)
**Volunteer Release:**
To reference this in the future, visit the [Volunteer Release & Waiver page.](https://sdrefugeetutoring.com/volunteer/waiver)

Thanks!!
