### ISSUE TITLE
[EXTREME HIGH - VOLUNTEER PORTAL] Upcoming Events: Make RSVP YES (or NO) button inactive once RSVP YES button has been activated 

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#86]
@JasonTheAdams Sorry I keep catching these? haha. The corresponding RSVP button needs to be deactivated if a current RSVP has been registered for that specific function. Right now, I can RSVP yes (or no) through the Portal to a Tutoring Event more than once. Meaning, I can keep pressing that RSVP YES button multiple times and it generates multiple notification emails. Although my RSVP does only show up once on the Event Page, not multiple times.
So if I RSVP YES to an event, then the RSVP YES button needs to be deactivated for that specific event until I press the RSVP NO button, and vice versa. It's late and I'm tired so I hope I have explained this appropriately!

**Comment by JasonTheAdams** [comment]
@dreazee So... you don't want to keep receiving the same email over and over??? Weird.

Hahah! I'll fix this now. 😉

**Comment by JasonTheAdams** [comment]
Fixed in df81dd2 — good catch, @dreazee! You don't ever need to apologize for helping to make this better. 😃

**Comment by dreazee** [comment]
@JasonTheAdams HAHA. I'm SO picky with my email inbox, I know. hahaha. I tested and re-tested this and it's all good! APPRECIATE YOU
