### ISSUE TITLE
[SUPER HIGH] VOLUNTEER PORTAL - DASHBOARD "Next Scheduled Event" Display Orientation Event Titles, Not Just Dates; Remove Organizer

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#87]
@JasonTheAdams Just looked at Volunteer Dashboard for the first time while having signed up for a future event! Essentially same thing we dealt with with issue #78 needs to be applied to the main Dashboard page.
https://sdrefugeetutoring.com/volunteer-portal/

1. Full Orientation Title needs to be displayed, not just date. 
2, Remove Organizer

I think that's it??

![Next Scheduled Event](https://user-images.githubusercontent.com/47679296/190272476-bdfbdda2-0e05-4faf-83e9-b84661f1d55a.png)

**Comment by JasonTheAdams** [comment]
Good catch! I've knocked this out in f6ed912

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/2024145/190943920-0254fad8-84af-4556-9dca-05bb46e80cd1.png">

**Comment by dreazee** [comment]
@JasonTheAdams  THANKS! It looks amazing.
