### ISSUE TITLE
[EXTREME HIGH] VOLUNTEER PORTAL - DASHBOARD - Next Scheduled Event is WONKY - 4 other issues

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#88]
@JasonTheAdams Oh boy... so I found some more stuff while exploring this area... The following pertain to the "Next Scheduled Event" box on Volunteer Portal - Dashboard 
https://sdrefugeetutoring.com/volunteer-portal/ 
There are a few issues with this one and I'm sick and don't have the time or bandwidth right now to make a new one for each of them - sorry!  I have tested and retested to lay out the issues here. 

1. "CANCEL RSVP" button does not work.
2. "Middle & High School" under "Tutoring" category isn't displayed correctly. (SEE SCREENSHOT BELOW) it doesn't like the ampersand special character!!  K-5th is displayed properly, though, so it is fine with the dash!
3. Dashboard does not populate/refresh on its own. Like if I RSVP for an event in Upcoming Events and then go to the Dashboard, the "Next Scheduled Event" does not show the event I just RSVP'd to. I need to do a hard refresh from my browser for that RSVP to pop up. This is confusing and we can't be asking everyone to refresh all the time... can we? 
4. Deleted RSVPs still showing up -  RSVP needs to be "delete permanently" from the backend in order for that deleted/no RSVP to disappear. This only happens if I manually delete an RSVP from the event page (by pressing the red x). Hopefully people will utilize the portal, but if there's an emergency, someone might still email me and it would be nice to be able to delete from the event page instead of going into the backend to delete permanently. If this needs to be done, though, THAT IS FINE. We can always remove the Red X button from the event page...  ? Breakdown of what was tested:
       a. If RSVP YES, then RSVP is deleted manually via event page, event still appears (BAD)
       b. If originally RSVP YES and then RSVP NO thru Portal, event does not appear (YAY)
       c. If originally RSVP NO, event does not appear (YAY)
       d. If originally RSVP NO and then RSVP YES, event appears (YAY)
       
Okay, I think that's everything I came across.... 

![Screenshot (58)](https://user-images.githubusercontent.com/47679296/190274949-19629f36-eebf-45d3-9023-f7272b2612f4.png)

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Excellent job testing things out! This is exactly what QA is for. 💪

Ok, I've resolved numbers 2 and 4: ampersand issue and trashed RSVPs still showing up.

For 1, I'm embarrassed to admit I apparently just straight up skipped past making that button do anything. Yikes. I'll knock that out tomorrow evening.

For 3, I see a similar request in #90. Since it's a bit of a complex issue and the two are tightly related, I'll respond more completely in that Issue. Once I resolve item 2 here I'll close this out.

**Comment by dreazee** [comment]
@JasonTheAdams !! I heard the Slack pings last night and knew it had to be you working on these issues... YAY! 

I tested 2 & 4 and it looks GREAT. 

I snort laughed when I read about 1. HAHAHAHAHA. Thank you for your honesty and providing me with that amusement.

QA is totally my thing. I LOVE IT SO MUCH. Lemme know if you need to hire a QA person for any of your other side jobs :smiley: :information_desk_person:

**Comment by JasonTheAdams** [comment]
Hey @dreazee!

Thanks so much for testing that out! I'm glad you got a good laugh. I had a solid facepalm when I saw the code and the utter lack of anything for the cancel button.

I'll definitely keep you in mind for other QA! You've been very thorough and helpful!

I'm afraid I didn't quite finish tonight. I made good progress — a dialog that prompts the user to make sure they _really_ want to cancel, and the back-end code to actual do the cancellation — all that's remaining is to hook the button up to the back-end code. I'll do my best to knock that out tomorrow or Wednesday and take this live!!

**Comment by dreazee** [comment]
ALL of this sounds great, @JasonTheAdams
I'm SUPER excited about this going live!! I'm getting giddy! I am very confident that everything is working and so so so so so excited for everyone to see it.

Keep me posted on the Cancel button and I'll look forward to testing it once it is finished... I'll keep my ears tuned in to that Slack notification ping!

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I just pushed the cancel button live! Imagine it actually doing something! 😂

As you're testing, here's how it _should_ work:
```mermaid
flowchart TD
A["User clicks the 'Cancel' button"] --> B["User is prompted with a window to confirm that they actually want to cancel — it includes event title"]
B -- "Keep RSVP or click off-window" --> C[Window closes]
B -- Cancel --> D[[RSVP is cancelled]]
D --> E{User has another upcoming event}
E -- Yes --> F[Next event is displayed]
E -- No --> G[Next event section is removed]

```

Let me know if you have any questions or run into any issues!

**Comment by dreazee** [comment]
Love your flow chart @JasonTheAdams ! I tested the flow all the ways and it works as shown. YAYYYYYYYYY
