### ISSUE TITLE
[SUPER HIGH - VOLUNTEER PORTAL] BACKGROUND CHECK - Change "Invited" Status display message

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#89]
@JasonTheAdams  The "Invited" status display message should be changed for clarity. The message is generated after a User clicks on "Complete Background Check" button. But then there is no real direction after that. One is not automatically directed to the Checkr site to complete the background check like they are when registering... 

Currently the "Invited" status message looks like:
You have been invited to take a background check, and your status is still pending. You can check your status on the Checkr website: {invitationUrl}

NEW "INVITED" STATUS message:
You have been invited to start a background check. Please click the link below to complete that process on the Checkr website or to check your status: {invitationUrl}

**Comment by JasonTheAdams** [comment]
Nice! Resolved in 2a2d85d

**Comment by dreazee** [comment]
Looks beautiful. Thanks, @JasonTheAdams !!
