### ISSUE TITLE
[SUPER HIGH---VOLUNTEER PORTAL] Requirements Page: UPDATE INTRO PARAGRAPH!

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#91]
Okay, so now I am looking at these little details @JasonTheAdams   Can't quit this QA life, man!
1. Code of Conduct is listed twice
2. Orientation isn't just one hour and actually varies in time.
3. Having this listed in reverse order (and in lower caps) is bothering me. (Did I tell you that I have a background in editing? haha)
4. Also, the green checkmarks are confusing because I thought that maybe those reflected the User's actual Volunteer Requirement status (I actually checked and found out that it doesn't. haha)
5. Also, does this (and any of the Portal text) live in the backend anywhere so that I can do it myself, if need be?

Original:
✅ Acceptance of our Code of Conduct
✅Acceptance of our Virtual Tutoring Code of Conduct
✅Attendance to a one-hour orientation session
✅Pass an online background check

Change to: 
💠 Pass an Online Background Check
💠 Attendance of an Orientation Session
💠 Acceptance of the Code of Conduct
💠 Acceptance of the Volunteer Release & Waiver

**Comment by dreazee** [comment]
Hey @JasonTheAdams Do you have a timeline for this fix? We have the most eyeballs on this page NOW, so would love for this to look fresh & profesh while everyone is actively using this page.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

My apologies for the delay. I'm admittedly pretty maxed on my September hours, so I'm struggling a bit to fit more in.

That said! I've got this resolved in 4b86493 and pushed the changes live.

Unfortunately, this text is all in code and not somewhere that can be changed by an admin. This is something we can change in the future if it feels important.

**Comment by dreazee** [comment]
@JasonTheAdams THANK YOU 🙏 grateful
