### ISSUE TITLE
[HIGH-VOLUNTEER PORTAL] Change "Failed" Background Check Message

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#92]
Since we put a pin in issue #75 @JasonTheAdams because we realized there was a lot more to it than what was originally realized, I decided to start a new thread to get this simple task completed of changing that failed message. It was displayed on someone's [Volunteer Status]([url](https://sdrefugeetutoring.com/volunteer-portal/requirements/)) and they actually sent an email to boardmembers@sdrt and ended up missing Tuesday's Returning Tutor Orientation (doh!). I figured out why this was happening and it shouldn't happen again, but want to cover my bases in case.

Please change the FAILED messaged from:
"Your background check did not clear. You are not allowed to tutor with us at this time. If you have questions about this at all, please contact [boardmembers@sdrefugeetutoring.com](mailto:boardmembers@sdrefugeetutoring.com)"

To NEW MESSAGE: 
 "Your Background Check or [Minors Registration Form](https://sdrefugeetutoring.com/volunteer/registration-for-minors/) is not up-to-date. For more information on how to start a new background check, please contact: [info@sdrefugeetutoring.com](mailto:info@sdrefugeetutoring.com)"

**Comment by JasonTheAdams** [comment]
Hey @dreazee!

I've resolved this in faae7ba and pushed the changes live. 👍
