### ISSUE TITLE
Volunteer Registrar Role for Users not operating correctly

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#93]
Alrighty @JasonTheAdams --- so this is an oldy... it looks like when the Event page RSVPs were spruced up to add extra functionality, it messed with the User's Volunteer Registrar Role.

This role should have access to the Current RSVPs (which it does now) but also to the "Attended?" column in order to check people in (which usually has a clickable Question Mark but is now completely blank when switching to this role.) <see screenshot below>

This role was created so a trusted User/volunteer could take over for me/Volunteer Coordinator if I am unable to attend an in-person tutoring session to check-in our Volunteers. So it is imperative that the Volunteer Registrar Role can both see the RSVP list and also have access to the "Attended?" column. Hopefully it's an easy fix!

![Volunteer-Registrar-view_Event-page-RSVP-list](https://user-images.githubusercontent.com/47679296/192623639-98d50181-8ed6-4488-a2cb-e015e55642da.png)

**Comment by JasonTheAdams** [comment]
Strangely enough, the styles file for the icons were missing for just that user role, which threw off how things were supposed to look. Weird.

Resolved in bd8ff03
