### ISSUE TITLE
[SUPER HIGH--PORTAL] Not Able to Access Volunteer Portal with iPad or iPhone

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#95]
@JasonTheAdams  Oh boy... so many people have reached out about this. Users are not able to access the Volunteer Portal from an iPhone or iPad, even when using a Chrome browser. (I keep telling people to not use Safari) 😨 Please tell me it's an easy fix? lol

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I checked out the portal on mobile and tablet. There were a number of styles that were broken so the site looked weird. I didn't see anything that would prevent someone from accessing the portal, though — you can access it just fine, it just wouldn't look right.

I pushed a bunch of styling improvements in 13f4c69 and tested it out on my iPhone.

I won't close this until we hear back from someone that it's working. If there are further issues please get as much information on what _exactly_ is breaking for the user.

Thank you!

**Comment by dreazee** [comment]
(AND THANK YOU @JasonTheAdams !!) Here's the screenshot I've received from a few people earlier today -- They log in and then go to the Portal and get the screen below. (And if we are able to add on that message to ask them to also include Device, Browser, and Operating System that would be AWESOME. Because that is always my next question)
![iPhone error Portal](https://user-images.githubusercontent.com/47679296/193732833-a71b0194-6772-44f3-b948-72f5eec99b8e.png)

**Comment by JasonTheAdams** [comment]
Interesting. Do you know the name and/or email of someone having the issue? Please DM them to me on Slack since these Issues are public.

**Comment by dreazee** [comment]
@JasonTheAdams I dm'd BUT I had someone send me a screenshot of an active Volunteer Portal today from an iPhone (yay!) so it looks like it is working... Let's put a pin in this and I will ask a few more people to check. But it seems like this was fixed... 🤞

**Comment by JasonTheAdams** [comment]
It's been almost a week. Let's close this for now and re-open if if the problem pops back up.
