### ISSUE TITLE
[Critical Priority - Vol. Portal] Allows RSVPs After Limit Number has Been Reached

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#97]
@JasonTheAdams We hit the max amount of rsvps for MS/HS today (set at 30) and Portal is still accepting "yes" RSVPs for that event... There should be a message in place when trying to RSVP 'yes", similar to that on the event page - https://sdrefugeetutoring.com/event/mshs-tutoring-2022-10-06/ 
But we can't close off the entire event through the portal in case someone needs to cancel/log in a 'no' rsvp

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Ohh! That's a _very_ good catch! I'm putting something together quickly. Here's what I've got:

**Event is at capacity and the volunteer has not RSVP'd:**
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2024145/194771756-5f026af2-99a1-48cc-b901-be87ddf7fe66.png">

**Event reached capacity while the user was viewing the page and they tried to RSVP as "yes":**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/2024145/194771834-5eca9630-1600-4e34-b7ce-460157793bfd.png">

**Event is at capacity and the volunteer has already RSPV'd yes:**
"Yes" is highlighted as usual, so the volunteer can still change their mind and RSVP "No".

**Event is not at capacity:**
Looks normal, as it has so far.

---

Please let me know if you'd like to make any changes to wording or anything!

**Comment by dreazee** [comment]
Heya @JasonTheAdams -- I'm just responding now to this because I wanted to get a chance to test before. But after re-reading your message and testing (and it failing), I think I misunderstood... I don't think this has been implemented yet and you were waiting on me to approve the wording?
I changed the RSVP number on this event in order to test --  https://sdrefugeetutoring.com/event/mshs-tutoring-2022-12-08/

**Comment by JasonTheAdams** [comment]
Hi @dreazee! Ah yes, I did not push this live as I wanted your feedback, first. Does this work the way you'd like? Do you want any of the messaging to change?

Once you confirm I'll push this live.

**Comment by dreazee** [comment]
oooOOOoooo @JasonTheAdams ...  Hmmm... Is there a way to just always have the YES button active instead of showing "AT LIMIT". And then if someone tries to RSVP "yes" to an event that is full, display that red message (but in the middle of the page and not at the bottom?). That red message I would love to say: "This event is full. To get on the waitlist please email info@sdrefugeetutoring.com"
OR... WAIT! **Is there a way to automatically trigger an email to me if someone is trying to RSVP to a session that is already full?** Then they wouldn't have to send an email and I can have this information. (like in case it is a veteran tutor and I need them to come to session regardless of the full status.) SORRY, I know it's tricky.
If the latter is possible, we can change that red message to "This event is full. You have been added to the waitlist & will be notified if there are any openings!"

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Hmm, so a totally different tactic, then. Hahah! I certainly want to drive towards what will actually serve you best so let's think through this for a moment.

If it is full, the user clicks "Yes", and the email is sent, at that point has an RSVP been created for that person? That is, if you were to view the event would you see the people in the "waitlist" included in that list? Should an RSVP be somehow differentiated as "waitlisted" instead of a clear "yes"? If so, how does the person know when they've been approved? And what would be the best way for you to approve them?

If you can walk me through — in a 1..2..3 list — how you would picture the flow going, I'm sure we can make it happen. I just want to make sure we have it fleshed out before I build it.

**Comment by dreazee** [comment]
@JasonTheAdams Clicking Yes if session is full would not generate an RSVP, only an email. I would keep track of interested tutors via the emails. Flow is below.
1. Session is Full & User Clicks Yes to RSVP
2a. Red message shows up in Middle of Screen saying: "This event is full. You have been added to the waitlist & will be notified if there are any openings!"
2b. Email is sent to info@ that "{User FirstName_LastName} Tried to RSVP to {Session Date} {Session Name}.
3a. YES changes to "AT LIMIT".

Is this easy or is this nuts? If way more difficult and time-consuming than previous idea, then that's fine.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Thank you for clearing that up and giving me a clear flow. I just pushed the changes to put this in place. Folks can still RSVP yes/no as usual when not at capacity, but when it reaches capacity they get the message you described which sends the email you described.

Let me know how this works! We can tweak it more if it's not quite fitting. I'll close this for now as I believe we're good to go, but feel free to open it back up if you think it needs more work. 👍

**Comment by dreazee** [comment]
@JasonTheAdams THANK YOU!!! We might not every need it again hahaha but at least it's there!

**Comment by dreazee** [comment]
Oh, and I tested this out @JasonTheAdams and it works! 🚀 YAY!
