### ISSUE TITLE
[HIGH] Re-work Front-End RSVP Table so that Delete & Action Columns are on Same Line when Copy/Paste RSVPs

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#98]
Oh boy...  @JasonTheAdams Here's another one!
The Front-End RSVP Table needs to be reworked so that the Style Doesn't Interfere with Accessing RSVP Names/Emails via Copy/Paste.
It seems that when changing the styles file to fix [Issue #93 (Resolved in bd8ff03 - changing styles for the front-end RSVP table)](https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/93#issuecomment-1272654299_), messed up my ability to easily copy/paste RSVPs onto a spreadsheet to be able to use functionally. Right now, after copy/paste, "Delete" & "Actions" show up on a separate line from Name & Email **(see spreadsheet - Right columns = how it looks now; left columns = how it looked previously)**. It used to paste onto the same line. This extra line REALLY interferes with my day-to-day and is making today a bit more of a struggle as there is a lot of deleting extra lines to get it ready to paste into a spreadsheet.  😭 
Here is what my process is/how I use the copy/paste:
1. Copy RSVPs from Front-End RSVP table & Paste into the same empty spreadsheet multiple times before a tutoring session (these are not saved)
2. Column of RSVP Emails are copied into various emails and the Attendance Spreadsheet
3. Column of RSVP Names are copied into the Attendance Spreadsheet

![Screenshot (98)](https://user-images.githubusercontent.com/47679296/195192692-13bc3081-219c-421c-bd72-ee53a681b90b.png)

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Hmm, that's interesting. I'm a bit surprised that it worked before. Controlling what is selectable and copy-able is tricky. Browsers make it difficult as it's not encouraged to control that. I did give it a go, but wasn't finding any reliable solutions.

So instead, I took another tactic entirely and added a "Download RSVPs" button:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/2024145/195485094-dfd6ca44-7298-4455-9f4d-ba76a382ecd7.png">

If you click that button it will generate a CSV of the list below, but only with the desired data. That way you can just click the button and download a CSV. You can either import that right into Google Drive, or copy and paste the contents of the file into your Google Sheet.

Being simple and only for managers, I went ahead and deployed this. Let me know if that works!

**Comment by dreazee** [comment]
Thanks @JasonTheAdams  Used this yesterday!
